name: 'MongoDB in GitHub Actions'
description: 'Start a MongoDB server (on default port 27017 or a custom port)'

branding:
  icon: 'database'
  color: 'green'

inputs:
  container-name:
    description: 'Name of the container to create (default "mongodb")'
    required: false
    default: 'mongodb'

  mongodb-version:
    description: 'MongoDB version to use (default "latest")'
    required: false
    default: 'latest'

  mongodb-replica-set:
    description: 'MongoDB replica set name (no replica set by default)'
    required: false
    default: ''

  mongodb-port:
    description: 'MongoDB port to use (default 27017)'
    required: false
    default: 27017

  mongodb-db:
    description: 'MongoDB db to create (default: none)'
    required: false
    default: ''

  mongodb-username:
    description: 'MongoDB root username (default: none)'
    required: false
    default: ''

  mongodb-password:
    description: 'MongoDB root password (default: none)'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mongodb-version }}
    - ${{ inputs.mongodb-replica-set }}
    - ${{ inputs.mongodb-port }}
    - ${{ inputs.mongodb-db }}
    - ${{ inputs.mongodb-username }}
    - ${{ inputs.mongodb-password }}
    - ${{ inputs.container-name }}